#:import utils kivy.utils
# .kv file implementation of the code
  
<textinp>:
    title: 'InputDialog'
    auto_dismiss: False
    id: test1
  
    # Using relative layout to arrange properly
    RelativeLayout:
        orientation: 'vertical'
        pos: self.pos
        size: root.size
        id: test2
  
        # Defining text input in .kv
        # And giving it the look . pos and features
        
        TextInput:
            id: input1
            hint_text:'Enter Protein in Grammes'
            pos_hint: {'center_x': 0.30, 'center_y': 0.205}
            size_hint: 0.50, 0.1
            on_text: app.process()

        TextInput:
            id: input2    
            hint_text:'Enter Carbs in Grammes'
            pos_hint: {'center_x': 0.30, 'center_y': 0.405}
            size_hint: 0.50, 0.1
            on_text: app.process()

        TextInput:
            id: input3    
            hint_text:'Enter Fats in Grammes'
            pos_hint: {'center_x': 0.30, 'center_y': 0.605}
            size_hint: 0.50, 0.1
            on_text: app.process()

        TextInput:
            id: input4    
            hint_text:'Enter Kcals'
            pos_hint: {'center_x': 0.30, 'center_y': 0.805}
            size_hint: 0.50, 0.1
            on_text: app.process()

        
        FloatLayout:     
            Button:
                id: plusbutton
                text:"ADD"
                background_color: 0, 0, 100, 1
                size_hint: 0.1, 0.1
                pos_hint: {"x":0.6, "top":0.85}
                on_release : app.plusbutton()  

        
        