#:import utils kivy.utils
# .kv file implementation of the code
  
<textinp>:
    title: 'InputDialog'
    auto_dismiss: False    
    id: test1
  
    # Using relative layout to arrange properly
    RelativeLayout:
        orientation: 'vertical'
        pos: self.pos
        size: root.size
        id: test2
  
        # Defining text input in .kv
        # And giving it the look . pos and features
        
        TextInput:
            id: input1
            input_filter: 'float'
            hint_text:'Enter Protein in Grammes'
            pos_hint: {'center_x': 0.28, 'center_y': 0.205}
            size_hint: 0.30, 0.1
            on_text: app.process()

        TextInput:
            id: input2    
            input_filter: 'float'
            hint_text:'Enter Carbs in Grammes'
            pos_hint: {'center_x': 0.28, 'center_y': 0.405}
            size_hint: 0.30, 0.1
            on_text: app.process()

        TextInput:
            id: input3
            input_filter: 'float'    
            hint_text:'Enter Fats in Grammes'
            pos_hint: {'center_x': 0.28, 'center_y': 0.605}
            size_hint: 0.30, 0.1
            on_text: app.process()

        TextInput:
            id: input4
            input_filter: 'float'    
            hint_text:'Enter Kcals'
            pos_hint: {'center_x': 0.28, 'center_y': 0.800}
            size_hint: 0.30, 0.1
            on_text: app.process()



        FloatLayout:     
            Button:
                id: plusbutton
                text:"ADD"
                background_color: 50, 1, 100, 0.5
                size_hint: 0.3, 0.1
                pos_hint: {"x":0.065, "top":0.15}
                on_release : app.add_data()


            Button:
                id: subbutton
                text:"SUB"
                background_color: 0, 1, 100, 0.5
                size_hint: 0.3, 0.1
                pos_hint: {"x":0.365, "top":0.15}
                on_release : app.remove_last_data()                

            Button:
                id: Kcalstotalsbutton
                text:"TOTKc"
                background_color: 50, 70, 25, 0.5
                size_hint: 0.1, 0.1
                pos_hint: {"x":0.85, "top":0.85}
                on_release : app.totalsbuttonKcal()              

            Button:
                id: clearbutton
                text:"CLEAR"
                background_color: 100, 1, 100, 0.5
                size_hint: 0.3, 0.1
                pos_hint: {"x":0.665, "top":0.15}
                on_release : app.clear_data()

            Button:
                id: totalsbutton
                text:"TOTcb"
                background_color: 50, 70, 25, 0.5
                size_hint: 0.1, 0.1
                pos_hint: {"x":0.85, "top":0.45}
                on_release :                   

            Button:
                id: totalsbutton
                text:"TOTf"
                background_color: 50, 70, 25, 0.5
                size_hint: 0.1, 0.1
                pos_hint: {"x":0.85, "top":0.65}
                on_release :                   

            Button:
                id: totalsbutton
                text:"TOTp"
                background_color: 50, 70, 25, 0.5
                size_hint: 0.1, 0.1
                pos_hint: {"x":0.85, "top":0.25}
                on_release :                   

            Label:
                id: outputKcals    
                size: 0.5,0.5
                pos_hint: {"x":0.1, "y":0.31}  # pos different from button layout
                text: 'TOT Kcals'
                background_color: 50,50,50,50



        