#:import utils kivy.utils
# .kv file implementation of the code
  
<textinp>:
    title: 'InputDialog'
    auto_dismiss: False    
    id: test1
  
    # Using relative layout to arrange properly
    RelativeLayout:
        orientation: 'vertical'
        pos: self.pos
        size: root.size
        id: test2


        Label:
            id: title
            size: 1.5,0.5
            font_size: 75
            markup: True
            bold : True     
            pos_hint: {'center_x': 0.5, 'center_y': 0.90}
            text: 'MacroTracker'
            background_color:(0,0,1,1)
            canvas.before:
                Color:
                    rgba:self.background_color
            color:(0,0.4,1,1) 
            outline_color:(1,1,1,1)
            outline_width:3

             
        TextInput:
            id: input1
            input_filter: 'float'
            hint_text:'Enter Protein'
            pos_hint: {'center_x': 0.24, 'center_y': 0.355}
            size_hint: 0.30, 0.1            

        TextInput:
            id: input2    
            input_filter: 'float'
            hint_text:'Enter Carbs'
            pos_hint: {'center_x': 0.24, 'center_y': 0.505}
            size_hint: 0.30, 0.1

        TextInput:
            id: input3
            input_filter: 'float'    
            hint_text:'Enter Fats'
            pos_hint: {'center_x': 0.24, 'center_y': 0.655}
            size_hint: 0.30, 0.1

        TextInput:
            id: input4
            input_filter: 'float'    
            hint_text:'Enter Kcals'
            pos_hint: {'center_x': 0.24, 'center_y': 0.800}
            size_hint: 0.30, 0.1



        FloatLayout:     

            Button:
                id: plusbutton
                text:"ADD"
                markup: True
                bold : True
                background_color: 1, 10, 100, 0.7
                size_hint: 0.25, 0.1
                pos_hint: {"x":0.645, "top":0.28}
                on_release : app.add_data(), app.clear_text_boxes()

            Button:
                id: subbutton
                text:"SUB"
                markup: True
                bold : True
                background_color: 1, 9, 100, 0.4          
                size_hint: 0.25, 0.1
                pos_hint: {"x":0.365, "top":0.28}
                on_release : app.remove_last_data(), app.clear_text_boxes()                

            Button:
                id: clearbutton
                text:"CLEAR"
                markup: True
                bold : True
                background_color: 0, 0, 100, 0.5
                size_hint: 0.25, 0.1
                pos_hint: {"x":0.085, "top":0.28}
                on_release : app.clear_data(), app.clear_text_boxes()           
           
            Button:
                id: Kcalstotalsbutton
                text:"TOTAL ALL"
                markup: True
                bold : True                
                background_color: 00, 10, 40, 0.5
                size_hint: 0.80, 0.1
                pos_hint: {"x":0.09, "top":0.15}
                on_release : app.totalsbuttonKcal(), app.clear_text_boxes()              



            Label:
                id: outputKcals    
                size: 0.5,0.5
                markup: True
                bold : True
                pos_hint: {"x":0.2, "y":0.30}  # pos different from button layout
                text: 'TOT Kcals'
                background_color: 50,50,50,50

            Label:
                id: TOTcbButton   
                size: 0.5,0.5
                markup: True
                bold : True
                pos_hint: {"x":0.2, "y":-0.005}  # pos different from button layout
                text: 'TOT Carbs'
                background_color: 50,50,50,50                

            Label:
                id: TOTfButton 
                size: 0.5,0.5
                markup: True
                bold : True                
                pos_hint: {"x":0.2, "y":0.15}  # pos different from button layout
                text: 'TOT Fats'
                background_color: 50,50,50,50  

            Label:
                id: TOTpButton 
                size: 0.5,0.5
                markup: True
                bold : True                
                pos_hint: {"x":0.2, "y":-0.15 }  # pos different from button layout
                text: 'TOT Protein'
                background_color: 50,50,50,50  